package io.autofixer.mangonaut.application.usecase

import io.autofixer.mangonaut.domain.model.Confidence
import io.autofixer.mangonaut.domain.model.ErrorEvent
import io.autofixer.mangonaut.domain.model.FixResult
import io.autofixer.mangonaut.domain.model.PrParams
import io.autofixer.mangonaut.domain.model.PrResult
import io.autofixer.mangonaut.domain.model.RepoId
import io.autofixer.mangonaut.domain.port.ScmProviderPort
import org.slf4j.LoggerFactory
import org.springframework.stereotype.Service

/**
 * Use Case that creates fix PRs based on analysis results.
 *
 * 1. Validate confidence
 * 2. Create new branch
 * 3. Commit file changes
 * 4. Create PR
 */
@Service
class CreateFixPullRequestUseCase(
    private val scmProviderPort: ScmProviderPort,
) {
    private val logger = LoggerFactory.getLogger(javaClass)

    data class Params(
        val errorEvent: ErrorEvent,
        val fixResult: FixResult,
        val repoId: RepoId,
        val defaultBranch: String,
        val branchPrefix: String,
        val labels: List<String>,
        val minConfidence: Confidence,
    )

    /**
     * Creates a fix PR.
     *
     * @return PR creation result, or null if not created
     */
    suspend operator fun invoke(params: Params): PrResult? {
        val fixResult = params.fixResult

        // Validate confidence
        if (!fixResult.canCreateAutoPr(params.minConfidence)) {
            logger.info(
                "Skipping PR creation: confidence={}, minRequired={}, hasChanges={}",
                fixResult.confidence,
                params.minConfidence,
                fixResult.changes.isNotEmpty(),
            )
            return null
        }

        // Generate branch name
        val branchName = PrParams.HeadBranch(
            "${params.branchPrefix}${params.errorEvent.id.value}"
        )

        // Check for duplicate PR
        if (scmProviderPort.hasOpenPR(params.repoId, branchName)) {
            logger.info("PR already exists for branch: {}", branchName.value)
            return null
        }

        // Create branch
        val baseBranch = PrParams.BaseBranch(params.defaultBranch)
        scmProviderPort.createBranch(params.repoId, baseBranch, branchName)

        // Commit file changes
        val validChanges = fixResult.changes.filter { it.hasChanges() }
        scmProviderPort.commitFiles(
            repoId = params.repoId,
            branch = branchName,
            changes = validChanges,
            message = "fix: ${params.errorEvent.title.value}\n\nAuto-generated by Mangonaut",
        )

        // Create PR
        val prParams = PrParams(
            title = PrParams.Title(fixResult.prTitle.value),
            body = PrParams.Body(fixResult.prBody.value),
            baseBranch = baseBranch,
            headBranch = branchName,
            labels = params.labels.map { PrParams.Label(it) },
        )

        return scmProviderPort.createPullRequest(params.repoId, prParams)
    }
}
