package io.autofixer.mangonaut.application.usecase

import io.autofixer.mangonaut.domain.model.Confidence
import io.autofixer.mangonaut.domain.model.ErrorEvent
import io.autofixer.mangonaut.domain.model.FixResult
import io.autofixer.mangonaut.domain.model.PrParams
import io.autofixer.mangonaut.domain.model.PrResult
import io.autofixer.mangonaut.domain.model.RepoId
import io.autofixer.mangonaut.domain.port.ScmProviderPort
import org.slf4j.LoggerFactory
import org.springframework.stereotype.Service

/**
 * 분석 결과를 기반으로 수정 PR을 생성하는 Use Case
 *
 * 1. 신뢰도 검증
 * 2. 새 브랜치 생성
 * 3. 파일 변경 커밋
 * 4. PR 생성
 */
@Service
class CreateFixPullRequestUseCase(
    private val scmProviderPort: ScmProviderPort,
) {
    private val logger = LoggerFactory.getLogger(javaClass)

    data class Params(
        val errorEvent: ErrorEvent,
        val fixResult: FixResult,
        val repoId: RepoId,
        val defaultBranch: String,
        val branchPrefix: String,
        val labels: List<String>,
        val minConfidence: Confidence,
    )

    /**
     * 수정 PR을 생성합니다.
     *
     * @return PR 생성 결과, 생성하지 않은 경우 null
     */
    suspend operator fun invoke(params: Params): PrResult? {
        val fixResult = params.fixResult

        // 신뢰도 검증
        if (!fixResult.canCreateAutoPr(params.minConfidence)) {
            logger.info(
                "Skipping PR creation: confidence={}, minRequired={}, hasChanges={}",
                fixResult.confidence,
                params.minConfidence,
                fixResult.changes.isNotEmpty(),
            )
            return null
        }

        // 브랜치 이름 생성
        val branchName = PrParams.HeadBranch(
            "${params.branchPrefix}${params.errorEvent.id.value}"
        )

        // 중복 PR 체크
        if (scmProviderPort.hasOpenPR(params.repoId, branchName)) {
            logger.info("PR already exists for branch: {}", branchName.value)
            return null
        }

        // 브랜치 생성
        val baseBranch = PrParams.BaseBranch(params.defaultBranch)
        scmProviderPort.createBranch(params.repoId, baseBranch, branchName)

        // 파일 변경 커밋
        val validChanges = fixResult.changes.filter { it.hasChanges() }
        scmProviderPort.commitFiles(
            repoId = params.repoId,
            branch = branchName,
            changes = validChanges,
            message = "fix: ${params.errorEvent.title.value}\n\nAuto-generated by Mangonaut",
        )

        // PR 생성
        val prParams = PrParams(
            title = PrParams.Title(fixResult.prTitle.value),
            body = PrParams.Body(fixResult.prBody.value),
            baseBranch = baseBranch,
            headBranch = branchName,
            labels = params.labels.map { PrParams.Label(it) },
        )

        return scmProviderPort.createPullRequest(params.repoId, prParams)
    }
}
